### ISSUE TITLE
External monitor on HDMI

### ISSUE THREAD

**Issue by romaindeveaud** [alxzoomer/msi-ge70-2pc-hackintosh#1]
Hi,

thanks for the great configuration, everything is running smoothly.
I wanted to plug an external monitor to the hdmi port, but the system crashes instantly.
Same if the monitor is plugged from the start, macOS won't boot and the computer would restart.

I tried a few things that didn't work, do you have any idea how I should approach this?

Thanks

**Comment by alxzoomer** [comment]
Hi,

I've used only built-in display and not experimented with HDMI. So don't have answer for you, sorry. You can ask Google or sites like https://www.tonymacx86.com and https://www.insanelymac.com/ about HDMI on our chipset Intel HM86 `intel hm86 hdmi hackintosh`. It's possible that solution already exists for similar laptop Asus k550jd etc.
