### ISSUE TITLE
Settings Screen is mixed

### ISSUE THREAD

**Issue by Pontifeximus** [alxzoomer/msi-ge70-2pc-hackintosh#4]
Hello and thanks for sharing your files. 
I have a GE70-2OE PC. After hdd installation, in the stage of arranging the settings (as location, time line, Privacy, etc etc) of the Hackintosh screen is funny and mixed. Which settings should I do ? 
Thanks.

**Comment by alxzoomer** [comment]
Hi,

Try this point from readme: For success work and avoiding 8 apples required UEFI+CSM settings in BIOS. 

HTH

**Comment by Pontifeximus** [comment]
Thank you.
